{% set name = "esi-utils-io" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esi-utils-io-{{ version }}.tar.gz
  sha256: 4091213d1660032c55243e4b928847c52d44d8d6266d8ff6a3fe5383916b7807

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - h5py >=3.1.0
    - numpy >=1.21
    - pandas >=1.0
    - pytz >=2021.3

test:
  imports:
    - esi_utils_io
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/esi-utils-io/
  summary: USGS Earthquake Impact Utilities for IO
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
